// Auto-generates TILE_TYPES entries from the atlases in src/assets/tiles/.
// Each atlas is split on a 132x132 grid; cells that are nearly empty
// (transparent) are skipped. Outputs src/game/tileTypes.generated.ts.
//
// Run: npm run extract-tiles

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PNG } from 'pngjs';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const CLIENT_ROOT = resolve(__dirname, '..');

const TILE = 132;
const ALPHA_THRESHOLD = 10;          // alpha > this counts as filled
const MIN_COVERAGE = 0.02;           // need ≥ 2% filled pixels to keep cell

// (filename, id prefix, human name prefix)
const ATLASES = [
  ['tiles/world.png', 'world', 'World'],
  ['tiles/cave.png',  'cave',  'Cave'],
  ['tiles/water.png', 'water', 'Water'],
];

const outEntries = [];

for (const [rel, idPrefix, namePrefix] of ATLASES) {
  const full = resolve(CLIENT_ROOT, 'src/assets', rel);
  const buf = readFileSync(full);
  const png = PNG.sync.read(buf);
  const { width: W, height: H, data } = png;

  const cols = Math.floor(W / TILE);
  const rows = Math.floor(H / TILE);
  console.log(`${basename(full)}: ${W}x${H} → grid ${cols}x${rows}`);

  let kept = 0;
  for (let gy = 0; gy < rows; gy++) {
    for (let gx = 0; gx < cols; gx++) {
      let filled = 0;
      const x0 = gx * TILE, y0 = gy * TILE;
      for (let y = y0; y < y0 + TILE; y++) {
        const rowStart = (y * W + x0) * 4;
        for (let x = 0; x < TILE; x++) {
          const a = data[rowStart + x * 4 + 3];
          if (a > ALPHA_THRESHOLD) filled++;
        }
      }
      const coverage = filled / (TILE * TILE);
      if (coverage < MIN_COVERAGE) continue;

      // Tighten the rect to the actual visible bounds within this cell, so
      // transparent padding doesn't push characters off the visible tile.
      let minX = x0 + TILE, maxX = x0 - 1;
      let minY = y0 + TILE, maxY = y0 - 1;
      for (let y = y0; y < y0 + TILE; y++) {
        const rowStart = (y * W + x0) * 4;
        for (let x = 0; x < TILE; x++) {
          const a = data[rowStart + x * 4 + 3];
          if (a > ALPHA_THRESHOLD) {
            const ax = x0 + x;
            if (ax < minX) minX = ax;
            if (ax > maxX) maxX = ax;
            if (y < minY) minY = y;
            if (y > maxY) maxY = y;
          }
        }
      }
      const tightX = minX, tightY = minY;
      const tightW = maxX - minX + 1, tightH = maxY - minY + 1;

      kept++;
      const id = `${idPrefix}_${gx}_${gy}`;
      const name = `${namePrefix} ${gx},${gy}`;
      outEntries.push({
        id, name,
        atlas: rel.replace(/\\/g, '/'),
        x: tightX, y: tightY, w: tightW, h: tightH,
      });
    }
  }
  console.log(`  → kept ${kept} non-empty tiles`);
}

const header = `// AUTO-GENERATED by scripts/extract-tiles.mjs — do not edit by hand.
// Run "npm run extract-tiles" to regenerate.
import type { TileType } from './tileTypes';

// Eagerly load every atlas PNG. Vite resolves these at build time into
// final hashed URLs we can look up by path.
const atlasUrls = import.meta.glob('../assets/tiles/*.png', {
  eager: true,
  import: 'default',
  query: '?url',
}) as Record<string, string>;

function atlasUrlFor(rel: string): string {
  const key = \`../assets/\${rel}\`;
  const url = atlasUrls[key];
  if (!url) throw new Error(\`Atlas not found: \${key}\`);
  return url;
}

type Entry = { id: string; name: string; atlas: string; x: number; y: number; w: number; h: number };

const ENTRIES: Entry[] = ${JSON.stringify(outEntries, null, 2)};

// Group key for the editor palette: atlas basename without extension
// ("tiles/world.png" → "world"). Derived at runtime so the extractor output
// stays minimal.
function groupFromAtlas(atlas: string): string {
  return atlas.split('/').pop()!.replace(/\\.png$/i, '');
}

export const GENERATED_TILES: TileType[] = ENTRIES.map((e) => ({
  id: e.id,
  name: e.name,
  url: atlasUrlFor(e.atlas),
  solid: true,
  srcRect: { x: e.x, y: e.y, w: e.w, h: e.h },
  group: groupFromAtlas(e.atlas),
}));
`;

const outPath = resolve(CLIENT_ROOT, 'src/game/tileTypes.generated.ts');
writeFileSync(outPath, header);
console.log(`\nWrote ${outPath} (${outEntries.length} tiles total)`);
