// AUTO-GENERATED by scripts/extract-tiles.mjs — do not edit by hand.
// Run "npm run extract-tiles" to regenerate.
import type { TileType } from './tileTypes';

// Eagerly load every atlas PNG. Vite resolves these at build time into
// final hashed URLs we can look up by path.
const atlasUrls = import.meta.glob('../assets/tiles/*.png', {
  eager: true,
  import: 'default',
  query: '?url',
}) as Record<string, string>;

function atlasUrlFor(rel: string): string {
  const key = `../assets/${rel}`;
  const url = atlasUrls[key];
  if (!url) throw new Error(`Atlas not found: ${key}`);
  return url;
}

type Entry = { id: string; name: string; atlas: string; x: number; y: number; w: number; h: number };

const ENTRIES: Entry[] = [
  {
    "id": "world_0_0",
    "name": "World 0,0",
    "atlas": "tiles/world.png",
    "x": 2,
    "y": 2,
    "w": 128,
    "h": 128
  },
  {
    "id": "world_1_0",
    "name": "World 1,0",
    "atlas": "tiles/world.png",
    "x": 132,
    "y": 0,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_2_0",
    "name": "World 2,0",
    "atlas": "tiles/world.png",
    "x": 264,
    "y": 0,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_3_0",
    "name": "World 3,0",
    "atlas": "tiles/world.png",
    "x": 396,
    "y": 0,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_4_0",
    "name": "World 4,0",
    "atlas": "tiles/world.png",
    "x": 528,
    "y": 0,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_5_0",
    "name": "World 5,0",
    "atlas": "tiles/world.png",
    "x": 660,
    "y": 0,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_6_0",
    "name": "World 6,0",
    "atlas": "tiles/world.png",
    "x": 792,
    "y": 0,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_7_0",
    "name": "World 7,0",
    "atlas": "tiles/world.png",
    "x": 924,
    "y": 0,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_8_0",
    "name": "World 8,0",
    "atlas": "tiles/world.png",
    "x": 1056,
    "y": 0,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_9_0",
    "name": "World 9,0",
    "atlas": "tiles/world.png",
    "x": 1188,
    "y": 0,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_0_1",
    "name": "World 0,1",
    "atlas": "tiles/world.png",
    "x": 0,
    "y": 132,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_1_1",
    "name": "World 1,1",
    "atlas": "tiles/world.png",
    "x": 132,
    "y": 132,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_3_1",
    "name": "World 3,1",
    "atlas": "tiles/world.png",
    "x": 396,
    "y": 132,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_4_1",
    "name": "World 4,1",
    "atlas": "tiles/world.png",
    "x": 528,
    "y": 132,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_5_1",
    "name": "World 5,1",
    "atlas": "tiles/world.png",
    "x": 660,
    "y": 132,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_6_1",
    "name": "World 6,1",
    "atlas": "tiles/world.png",
    "x": 792,
    "y": 132,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_8_1",
    "name": "World 8,1",
    "atlas": "tiles/world.png",
    "x": 1056,
    "y": 132,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_9_1",
    "name": "World 9,1",
    "atlas": "tiles/world.png",
    "x": 1188,
    "y": 132,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_0_2",
    "name": "World 0,2",
    "atlas": "tiles/world.png",
    "x": 0,
    "y": 264,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_1_2",
    "name": "World 1,2",
    "atlas": "tiles/world.png",
    "x": 132,
    "y": 264,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_2_2",
    "name": "World 2,2",
    "atlas": "tiles/world.png",
    "x": 264,
    "y": 264,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_3_2",
    "name": "World 3,2",
    "atlas": "tiles/world.png",
    "x": 396,
    "y": 264,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_5_2",
    "name": "World 5,2",
    "atlas": "tiles/world.png",
    "x": 660,
    "y": 264,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_6_2",
    "name": "World 6,2",
    "atlas": "tiles/world.png",
    "x": 792,
    "y": 264,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_7_2",
    "name": "World 7,2",
    "atlas": "tiles/world.png",
    "x": 924,
    "y": 264,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_8_2",
    "name": "World 8,2",
    "atlas": "tiles/world.png",
    "x": 1056,
    "y": 264,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_9_2",
    "name": "World 9,2",
    "atlas": "tiles/world.png",
    "x": 1188,
    "y": 264,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_0_3",
    "name": "World 0,3",
    "atlas": "tiles/world.png",
    "x": 0,
    "y": 396,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_1_3",
    "name": "World 1,3",
    "atlas": "tiles/world.png",
    "x": 132,
    "y": 396,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_2_3",
    "name": "World 2,3",
    "atlas": "tiles/world.png",
    "x": 264,
    "y": 396,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_3_3",
    "name": "World 3,3",
    "atlas": "tiles/world.png",
    "x": 396,
    "y": 396,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_4_3",
    "name": "World 4,3",
    "atlas": "tiles/world.png",
    "x": 528,
    "y": 396,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_5_3",
    "name": "World 5,3",
    "atlas": "tiles/world.png",
    "x": 660,
    "y": 396,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_7_3",
    "name": "World 7,3",
    "atlas": "tiles/world.png",
    "x": 924,
    "y": 396,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_8_3",
    "name": "World 8,3",
    "atlas": "tiles/world.png",
    "x": 1056,
    "y": 396,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_9_3",
    "name": "World 9,3",
    "atlas": "tiles/world.png",
    "x": 1188,
    "y": 396,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_0_4",
    "name": "World 0,4",
    "atlas": "tiles/world.png",
    "x": 0,
    "y": 528,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_1_4",
    "name": "World 1,4",
    "atlas": "tiles/world.png",
    "x": 132,
    "y": 528,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_2_4",
    "name": "World 2,4",
    "atlas": "tiles/world.png",
    "x": 264,
    "y": 528,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_3_4",
    "name": "World 3,4",
    "atlas": "tiles/world.png",
    "x": 396,
    "y": 528,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_4_4",
    "name": "World 4,4",
    "atlas": "tiles/world.png",
    "x": 528,
    "y": 528,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_5_4",
    "name": "World 5,4",
    "atlas": "tiles/world.png",
    "x": 660,
    "y": 528,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_6_4",
    "name": "World 6,4",
    "atlas": "tiles/world.png",
    "x": 792,
    "y": 528,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_7_4",
    "name": "World 7,4",
    "atlas": "tiles/world.png",
    "x": 924,
    "y": 528,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_9_4",
    "name": "World 9,4",
    "atlas": "tiles/world.png",
    "x": 1188,
    "y": 528,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_0_5",
    "name": "World 0,5",
    "atlas": "tiles/world.png",
    "x": 0,
    "y": 660,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_1_5",
    "name": "World 1,5",
    "atlas": "tiles/world.png",
    "x": 132,
    "y": 660,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_2_5",
    "name": "World 2,5",
    "atlas": "tiles/world.png",
    "x": 264,
    "y": 660,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_4_5",
    "name": "World 4,5",
    "atlas": "tiles/world.png",
    "x": 528,
    "y": 660,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_5_5",
    "name": "World 5,5",
    "atlas": "tiles/world.png",
    "x": 660,
    "y": 660,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_6_5",
    "name": "World 6,5",
    "atlas": "tiles/world.png",
    "x": 792,
    "y": 660,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_7_5",
    "name": "World 7,5",
    "atlas": "tiles/world.png",
    "x": 924,
    "y": 660,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_8_5",
    "name": "World 8,5",
    "atlas": "tiles/world.png",
    "x": 1056,
    "y": 660,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_9_5",
    "name": "World 9,5",
    "atlas": "tiles/world.png",
    "x": 1188,
    "y": 660,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_1_6",
    "name": "World 1,6",
    "atlas": "tiles/world.png",
    "x": 132,
    "y": 792,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_2_6",
    "name": "World 2,6",
    "atlas": "tiles/world.png",
    "x": 264,
    "y": 792,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_3_6",
    "name": "World 3,6",
    "atlas": "tiles/world.png",
    "x": 396,
    "y": 792,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_4_6",
    "name": "World 4,6",
    "atlas": "tiles/world.png",
    "x": 528,
    "y": 792,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_5_6",
    "name": "World 5,6",
    "atlas": "tiles/world.png",
    "x": 660,
    "y": 792,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_6_6",
    "name": "World 6,6",
    "atlas": "tiles/world.png",
    "x": 792,
    "y": 792,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_7_6",
    "name": "World 7,6",
    "atlas": "tiles/world.png",
    "x": 924,
    "y": 792,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_8_6",
    "name": "World 8,6",
    "atlas": "tiles/world.png",
    "x": 1056,
    "y": 792,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_9_6",
    "name": "World 9,6",
    "atlas": "tiles/world.png",
    "x": 1188,
    "y": 792,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_0_7",
    "name": "World 0,7",
    "atlas": "tiles/world.png",
    "x": 0,
    "y": 924,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_1_7",
    "name": "World 1,7",
    "atlas": "tiles/world.png",
    "x": 132,
    "y": 924,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_3_7",
    "name": "World 3,7",
    "atlas": "tiles/world.png",
    "x": 396,
    "y": 924,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_4_7",
    "name": "World 4,7",
    "atlas": "tiles/world.png",
    "x": 528,
    "y": 924,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_5_7",
    "name": "World 5,7",
    "atlas": "tiles/world.png",
    "x": 660,
    "y": 924,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_6_7",
    "name": "World 6,7",
    "atlas": "tiles/world.png",
    "x": 792,
    "y": 924,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_7_7",
    "name": "World 7,7",
    "atlas": "tiles/world.png",
    "x": 924,
    "y": 924,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_8_7",
    "name": "World 8,7",
    "atlas": "tiles/world.png",
    "x": 1056,
    "y": 924,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_9_7",
    "name": "World 9,7",
    "atlas": "tiles/world.png",
    "x": 1188,
    "y": 924,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_0_8",
    "name": "World 0,8",
    "atlas": "tiles/world.png",
    "x": 0,
    "y": 1056,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_1_8",
    "name": "World 1,8",
    "atlas": "tiles/world.png",
    "x": 132,
    "y": 1056,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_2_8",
    "name": "World 2,8",
    "atlas": "tiles/world.png",
    "x": 264,
    "y": 1056,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_3_8",
    "name": "World 3,8",
    "atlas": "tiles/world.png",
    "x": 396,
    "y": 1056,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_5_8",
    "name": "World 5,8",
    "atlas": "tiles/world.png",
    "x": 660,
    "y": 1056,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_6_8",
    "name": "World 6,8",
    "atlas": "tiles/world.png",
    "x": 792,
    "y": 1056,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_7_8",
    "name": "World 7,8",
    "atlas": "tiles/world.png",
    "x": 924,
    "y": 1056,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_8_8",
    "name": "World 8,8",
    "atlas": "tiles/world.png",
    "x": 1056,
    "y": 1056,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_0_9",
    "name": "World 0,9",
    "atlas": "tiles/world.png",
    "x": 0,
    "y": 1188,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_1_9",
    "name": "World 1,9",
    "atlas": "tiles/world.png",
    "x": 132,
    "y": 1188,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_2_9",
    "name": "World 2,9",
    "atlas": "tiles/world.png",
    "x": 264,
    "y": 1188,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_3_9",
    "name": "World 3,9",
    "atlas": "tiles/world.png",
    "x": 396,
    "y": 1188,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_4_9",
    "name": "World 4,9",
    "atlas": "tiles/world.png",
    "x": 528,
    "y": 1188,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_5_9",
    "name": "World 5,9",
    "atlas": "tiles/world.png",
    "x": 660,
    "y": 1188,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_7_9",
    "name": "World 7,9",
    "atlas": "tiles/world.png",
    "x": 924,
    "y": 1188,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_8_9",
    "name": "World 8,9",
    "atlas": "tiles/world.png",
    "x": 1056,
    "y": 1188,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_9_9",
    "name": "World 9,9",
    "atlas": "tiles/world.png",
    "x": 1188,
    "y": 1188,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_0_10",
    "name": "World 0,10",
    "atlas": "tiles/world.png",
    "x": 0,
    "y": 1320,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_1_10",
    "name": "World 1,10",
    "atlas": "tiles/world.png",
    "x": 132,
    "y": 1320,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_2_10",
    "name": "World 2,10",
    "atlas": "tiles/world.png",
    "x": 264,
    "y": 1320,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_3_10",
    "name": "World 3,10",
    "atlas": "tiles/world.png",
    "x": 396,
    "y": 1320,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_4_10",
    "name": "World 4,10",
    "atlas": "tiles/world.png",
    "x": 528,
    "y": 1320,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_5_10",
    "name": "World 5,10",
    "atlas": "tiles/world.png",
    "x": 660,
    "y": 1320,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_6_10",
    "name": "World 6,10",
    "atlas": "tiles/world.png",
    "x": 792,
    "y": 1320,
    "w": 132,
    "h": 132
  },
  {
    "id": "world_7_10",
    "name": "World 7,10",
    "atlas": "tiles/world.png",
    "x": 924,
    "y": 1320,
    "w": 132,
    "h": 132
  },
  {
    "id": "cave_0_0",
    "name": "Cave 0,0",
    "atlas": "tiles/cave.png",
    "x": 2,
    "y": 2,
    "w": 128,
    "h": 128
  },
  {
    "id": "cave_0_1",
    "name": "Cave 0,1",
    "atlas": "tiles/cave.png",
    "x": 0,
    "y": 212,
    "w": 132,
    "h": 52
  },
  {
    "id": "cave_1_1",
    "name": "Cave 1,1",
    "atlas": "tiles/cave.png",
    "x": 135,
    "y": 153,
    "w": 129,
    "h": 111
  },
  {
    "id": "cave_0_2",
    "name": "Cave 0,2",
    "atlas": "tiles/cave.png",
    "x": 0,
    "y": 264,
    "w": 132,
    "h": 132
  },
  {
    "id": "cave_1_2",
    "name": "Cave 1,2",
    "atlas": "tiles/cave.png",
    "x": 132,
    "y": 264,
    "w": 132,
    "h": 132
  },
  {
    "id": "water_0_0",
    "name": "Water 0,0",
    "atlas": "tiles/water.png",
    "x": 2,
    "y": 2,
    "w": 128,
    "h": 128
  },
  {
    "id": "water_1_0",
    "name": "Water 1,0",
    "atlas": "tiles/water.png",
    "x": 132,
    "y": 13,
    "w": 132,
    "h": 119
  },
  {
    "id": "water_0_1",
    "name": "Water 0,1",
    "atlas": "tiles/water.png",
    "x": 0,
    "y": 132,
    "w": 132,
    "h": 132
  }
];

// Group key for the editor palette: atlas basename without extension
// ("tiles/world.png" → "world"). Derived at runtime so the extractor output
// stays minimal.
function groupFromAtlas(atlas: string): string {
  return atlas.split('/').pop()!.replace(/\.png$/i, '');
}

export const GENERATED_TILES: TileType[] = ENTRIES.map((e) => ({
  id: e.id,
  name: e.name,
  url: atlasUrlFor(e.atlas),
  solid: true,
  srcRect: { x: e.x, y: e.y, w: e.w, h: e.h },
  group: groupFromAtlas(e.atlas),
}));
